version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    command: npm run dev  # Use npm run dev for hot-reloading
    env_file:
      - ./client/.env.docker
    volumes:
      - ./client:/usr/src/app  # Sync host and container directories          
      - /usr/src/app/.output            
      - /usr/src/app/node_modules       
    ports:
      - "3000:3000"  # Expose Nuxt.js development server port
    networks:
      - app-network

  api:
    build:
      context: .
    container_name: api
    command: php artisan serve --host=0.0.0.0 --port=8001  # Serve Laravel on port 8001
    volumes:
      - .:/var/www
      - /var/www/vendor
    env_file:
      - .env.docker
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - /var/www/vendor
    depends_on:
      - client
      - api
    networks:
      - app-network
    
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
