version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - ./client:/usr/src/app          
      - /usr/src/app/.output            
      - /usr/src/app/node_modules       
    
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
      - /var/www/vendor
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - /var/www/vendor
    depends_on:
      - client
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
